blank_issues_enabled: false
contact_links:
  - name: PawsomeVencord Support Server
    url: https://discord.gg/w9jVtzNx4c
    about: If you need help regarding PawsomeVencord, please join our support server!
  - name: PawsomeVencord Installer
    url: https://github.com/enzomtpYT/PawsomeVencordInstaller
    about: You can find the PawsomeVencord Installer here
